name: home_care
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.2
  firebase_core: ^3.0.0   # Use a compatible version
  firebase_auth: ^5.0.0    # Downgraded to match compatibility
  cloud_firestore: ^5.0.0   # Downgraded to match compatibility
  intl: ^0.18.1
  url_launcher: ^6.0.20
  flutter_phone_direct_caller: ^2.1.1
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/ac.png
    - images/speaker.png
    - images/apple.png
    - images/logo.png
