// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfAfW0Xx2oSs1oif9-by2wNtTVQ1MnMEs',
    appId: '1:927793168537:web:c205a832fbb7482761f808',
    messagingSenderId: '927793168537',
    projectId: 'home-care-app-e1f9d',
    authDomain: 'home-care-app-e1f9d.firebaseapp.com',
    storageBucket: 'home-care-app-e1f9d.firebasestorage.app',
    measurementId: 'G-0HYMYFQ4XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU7Vr7rsq-1eR-E-odAEBNzvr8SnToQpg',
    appId: '1:927793168537:android:e858fe825c55bdbb61f808',
    messagingSenderId: '927793168537',
    projectId: 'home-care-app-e1f9d',
    storageBucket: 'home-care-app-e1f9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANkJ0vgxNyDm7h5eyP5oX_VzXOt8osgG0',
    appId: '1:927793168537:ios:9d803514622c401f61f808',
    messagingSenderId: '927793168537',
    projectId: 'home-care-app-e1f9d',
    storageBucket: 'home-care-app-e1f9d.firebasestorage.app',
    iosBundleId: 'com.example.homeCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANkJ0vgxNyDm7h5eyP5oX_VzXOt8osgG0',
    appId: '1:927793168537:ios:9d803514622c401f61f808',
    messagingSenderId: '927793168537',
    projectId: 'home-care-app-e1f9d',
    storageBucket: 'home-care-app-e1f9d.firebasestorage.app',
    iosBundleId: 'com.example.homeCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfAfW0Xx2oSs1oif9-by2wNtTVQ1MnMEs',
    appId: '1:927793168537:web:8f079de63ab66fd661f808',
    messagingSenderId: '927793168537',
    projectId: 'home-care-app-e1f9d',
    authDomain: 'home-care-app-e1f9d.firebaseapp.com',
    storageBucket: 'home-care-app-e1f9d.firebasestorage.app',
    measurementId: 'G-6NL14F32YE',
  );
}
